### ISSUE TITLE
Fix typos in paper.md

### ISSUE THREAD

**Issue by ahasverus** [FRBCesab/chessboard#7]
Fix the following typos in `paper.md` as mentionned in #2:

**Lines 9/10 and Lines 29/30**

- Replace "_It can handle directed (asymmetric) and undirected (**symmetrical**) spatial (or **not spatial**) networks connection_" by "_It can handle directed (asymmetric) and undirected (**symmetric**) spatial (or **non-spatial**) **network connections**_".

**Comment by Pentaonia** [comment]
When you adjust **not spatial** to **non-spatial**, you should consider adjusting the comment in the chunk between 49/50, too.

- **non spatial** --> **non-spatial**
