### ISSUE TITLE
JOSS reviev - Contributors

### ISSUE THREAD

**Issue by gsapijaszko** [FRBCesab/chessboard#8]
Hi,

there is a discrepancy between article authors (Nicolas Casajus, Érica Rievrs Borges, Éric Tabacchi, Guillaume
Fried, and Nicolas Mouquet) and Authors in DESCRIPTION file:

    Authors@R: c(
        person(given   = "Nicolas",
               family  = "Casajus",
               role    = c("aut", "cre", "cph"),
               email   = "nicolas.casajus@fondationbiodiversite.fr",
               comment = c(ORCID = "0000-0002-5537-5294")))

Either please expand DESCRIPTION file for contributors, either mention the role of the co-authors in article.

Regards,
Grzegorz

**Comment by ahasverus** [comment]
Hi Grzegorz,

Thanks for pointing out this discrepency;

I decided to expand the `DESCRIPTION` file by adding all authors of the JOSS paper as authors of the package as they contributed in its development.
I also updated these files: `README.Rmd`, `README.md`, `CITATION`, `CITATION.cff`.

Nicolas

**Comment by gsapijaszko** [comment]
Thank you, Nicolas. :)
